import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  btnCreate: {
    width: 50,
    height: 50,
    backgroundColor: '#6600E7',
    borderRadius: 50 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  input: {
    backgroundColor: '#ECECEC',
    height: 50,
    borderRadius: 50 / 2,
    paddingHorizontal: 20,
    elevation: 5,
    flex: 1,
  },
  container: {
    maxWidth: 480,
    alignSelf: 'center',
    width: '100%',
  },
  textEdit: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 17,
  },
  btnEdit: {
    backgroundColor: '#6600E7',
    height: 45,
    width: 100,
    borderRadius: 45 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    elevation: 3,
    overflow: 'hidden',
  },
  inputEdit: {
    borderBottomWidth: 1,
    borderBottomColor: '#6600E7',
    width: '75%',
    alignSelf: 'center',
    paddingHorizontal: 10,
    color: 'black',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewModal: {
    backgroundColor: 'white',
    padding: 20,
    width: '80%',
    borderRadius: 20,
    elevation: 5,
    maxWidth: 520,
  },
  modalContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  backdrop: {
    backgroundColor: 'black',
    opacity: 0.25,
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  viewLine: {
    backgroundColor: 'black',
    width: 2,
    height: 40,
    marginHorizontal: 15,
    opacity: 0.5,
  },
  btnOption: {
    backgroundColor: '#6600E7',
    width: 35,
    height: 35,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  textTask: {
    color: 'black',
    fontWeight: '500',
    fontSize: 16,
    flex: 1,
  },
  viewTaskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: 20,
  },
  viewInput: {
    flexDirection: 'row',
    margin: 20,
  },
  viewTask: {
    flex: 1,
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textHeader: {
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
    marginHorizontal: 10,
  },
  viewHeader: {
    flexDirection: 'row',
    backgroundColor: '#6600E7',
    height: 50,
    elevation: 5,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
});
